// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsISHBaVXnqxKNrUHscDK7PxRTQ0qS86M',
    appId: '1:465639624470:web:a94bf73abdfb5184508a37',
    messagingSenderId: '465639624470',
    projectId: 'eco-scan-app-bektas',
    authDomain: 'eco-scan-app-bektas.firebaseapp.com',
    storageBucket: 'eco-scan-app-bektas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC97y4hE_OHqkJoIDqj21OsCXd-gY1uQ3s',
    appId: '1:465639624470:android:fe4cccf5606f6f5e508a37',
    messagingSenderId: '465639624470',
    projectId: 'eco-scan-app-bektas',
    storageBucket: 'eco-scan-app-bektas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEb9Z4D0guSJnAxPzHgukEQB28M3XHlQ4',
    appId: '1:465639624470:ios:3f32df93a0419850508a37',
    messagingSenderId: '465639624470',
    projectId: 'eco-scan-app-bektas',
    storageBucket: 'eco-scan-app-bektas.firebasestorage.app',
    iosBundleId: 'com.example.ecoscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEb9Z4D0guSJnAxPzHgukEQB28M3XHlQ4',
    appId: '1:465639624470:ios:3f32df93a0419850508a37',
    messagingSenderId: '465639624470',
    projectId: 'eco-scan-app-bektas',
    storageBucket: 'eco-scan-app-bektas.firebasestorage.app',
    iosBundleId: 'com.example.ecoscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsISHBaVXnqxKNrUHscDK7PxRTQ0qS86M',
    appId: '1:465639624470:web:dda414b6f361d1b7508a37',
    messagingSenderId: '465639624470',
    projectId: 'eco-scan-app-bektas',
    authDomain: 'eco-scan-app-bektas.firebaseapp.com',
    storageBucket: 'eco-scan-app-bektas.firebasestorage.app',
  );
}
